apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: IPC211
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: "root"
          passwd: "rjpAK1K7Qpc6AafXm9Xg"
    elemental:
      install:
        reboot: true
        device: dev/sda
        debug: true
      registration:
        emulate-tpm: true
        emulated-tpm-seed: 1
  machineName: IPC211
  machineInventoryLabels:
    location: "nuernberg"
