apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: ecsdev
  namespace: fleet-default
spec:
  rkeConfig:
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: ecsdevselector
        name: ecsdev
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
  kubernetesVersion: v1.23.7+k3s1